### ISSUE TITLE
Underlying ALM rebalance for Ichi

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-subgraph#8]
* AlmFeeHistory immutable entity
  * alm (address)
  * protocol (name)
  * timestamp
  * totalAsset0
  * totalAsset1
  * totalUsd
  * fee0
  * fee1
  * feeUsd
  * isRebalance
  * APRLastEvent (between last and prelast)
 

```
event Rebalance(
        int24 tick,
        uint256 totalAmount0,
        uint256 totalAmount1,
        uint256 feeAmount0,
        uint256 feeAmount1,
        uint256 totalSupply
    );
```

**Comment by JodsMigel** [comment]
Done

**Comment by JodsMigel** [comment]
Updated issue
